name: Recovery Builder - TWRP

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Manifest Branch'
        required: true
        default: 'twrp-14'
        type: choice
        options:
        - twrp-14
        - twrp-12.1
        - twrp-11
      DEVICE_TREE:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/khusnan21/device_itel_P1102GT_twrp'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Device Path'
        required: true
        default: 'device/itel/P1102GT'
      DEVICE_NAME:
        description: 'Device Codename'
        required: true
        default: 'P1102GT'
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install gperf gcc-multilib g++-multilib libc6-dev lib32ncurses5-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache liblz4-tool libncurses5-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev python3

    - name: Install OpenJDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install repo tool
      run: |
        curl https://raw.githubusercontent.com/GerritCodeReview/git-repo/refs/heads/main/repo > repo
        chmod a+rx repo
        sudo mv repo /usr/bin/

    - name: Initialize Repo
      run: |
        mkdir android-recovery
        cd android-recovery
        if [ "${{ github.event.inputs.MANIFEST_BRANCH }}" = "twrp-14" ]; then
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14 -g default,-mips,-darwin,-notdefault
        else
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        fi

    - name: Repo Sync
      run: |
        cd android-recovery
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
